global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: "ocr-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["ocr-worker:8080"]

  - job_name: "rag-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["rag-service:8080"]
